### PR TITLE
chore: Update build system

### PR DESCRIPTION
**Pull request by lhw**
- Updating all action versions across the board
- Removed the no-op lint step
- Added a built-test step
- Added darwin/* back to goreleaser (Closes: #154)

### CODE REVIEW

**Comment by evgenkisel** [comment]
@lhw thank you for the PR!
Who could help to review and merged it?

**Comment by evgenkisel** [comment]
any updates?

**Comment by lhw** [comment]
I'd rather not self-approve. But in general this should be fine now

**Comment by bitkeks** [comment]
LGTM, thanks @lhw

**Pull request merged**
