### PR TITLE
Fix Katello product resource API call

### LINKED ISSUE #54: foreman_katello_product is broken
It seems recent versions of Katello have made `organization_id` a required parameter. The provider needs to be updated to handle this.

[GET /katello/api/products](https://theforeman.org/plugins/katello/3.17/api/apidoc/v2/products/index.html)

I've started investigating this. I'm thinking to use the ID in the provider config rather than make it an explicit parameter of the resource.

### PR DESCRIPTION
**Pull request by bitkeks**
foreman_katello_product used an old wrapper that did not include location_id and organization_id in the payload of calls towards the API.

Resolves #54

### CODE REVIEW

**Comment by bitkeks** [comment]
This one's ready for its purpose to fix the katello product resource calls. It also adds handling for the async "ForemanTask" objects, which are the return type in the Katello API.

To not further bloat this PR, I will continue on another branch for #141

**Comment by bitkeks** [comment]
@lhw would you like me to split the PR into two separate PRs, one containing the fix for katello_product and the other for the Katello async ForemanTasks?

**Review by lhw — APPROVED** [review]
No. It's fine. Terraform can't really do async by nature. So waiting for a response to a started task is the right way to handle it.

**Comment by lukry59** [comment]
Hello,

Any news on the progress of this PR ?

Regards,
G.

**Comment by bitkeks** [comment]
Merged, had no conflicts - please test!

**Pull request merged**
